set -o emacs # emacs style
source ~/antigen/antigen.zsh

antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle extract 
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle skywind3000/z.lua
antigen bundle cargo
antigen bundle kubectl
# TODO fix me
# antigen bundle zsh-users/zsh-autosuggestions # tab and crash
# # Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
# y copy to system clipboard
antigen bundle "https://github.com/kutsan/zsh-system-clipboard.git"

# Load the theme
# https://github.com/zsh-users/antigen/issues/675#issuecomment-452764451
THEME=robbyrussell
antigen list | grep $THEME; if [ $? -ne 0 ]; then antigen theme $THEME; fi

# Tell Antigen that you're done.
antigen apply


export PATH=~/bin:$PATH

export PATH=$PATH:/usr/local/go/bin:~/.local/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/oaa/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/home/oaa/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/oaa/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/oaa/bin/google-cloud-sdk/completion.zsh.inc'; fi


alias gpm="git pull origin master"
alias gpd="git pull origin develop"

alias dl="aria2c -s16 -x16 -k1M"

# rust
source $HOME/.cargo/env

eval $(thefuck --alias)

gitclone () {
    echo "git clone by https://gitclone.com/"
    url=$1
    proxyed_url=$(sed 's/https:\/\//https:\/\/gitclone.com\//g'<<< $url)
    echo "origin url $url"
    echo "proxyed url $proxyed_url"
    git clone $proxyed_url
}


# load all shell-actions

load_awesome_shell_actions() {
    awesome_shell_actions_path=$1
    if [ -d $awesome_shell_actions_path ] 
    then 
        echo "find awesome-shell-actions in ${awesome_shell_actions_path} start load"
        . $awesome_shell_actions_path/scripts/awesome-shell-actions.sh
        awesome-shell-actions-load $awesome_shell_actions_path
    else
        echo "cloud not find awesome-shell-actions in $awesome_shell_actions_path ignore"
    fi
}


load_awesome_shell_actions ~/.zsh/awesome-shell-actions

mx() {
    eval $(print -rl ${(k)functions_source[(R)*awesome*]} | fzf)
    zle reset-prompt
    # print -rl ${(k)functions_source[(R)*awesome*]} | fzf
}

zle -N  mx
bindkey ',xm' mx



alias vim=nvim



ME=$(who|head -n 1 | awk '{print $1}')
HOME=/home/${ME}


## gvm
source ~/.gvm/scripts/gvm # comflict with zsh-autocomplete?

export PATH=~/sm/scripts:$PATH
export PATH=/usr/local/nginx:$PATH
export PATH=/opt/openresty/bin:$PATH

export S_CONFIG_DIR=~/sm/pv/s-config



## https://unix.stackexchange.com/questions/499317/prevent-completion-of-files-for-make-command-in-zsh-shell
zstyle ':completion:*:*:make:*' tag-order 'targets'
autoload -U compinit && compinit
alias wget-proxy="wget  -e use_proxy=on -e http_proxy=http://127.0.0.1:20172 -e https_proxy=http://127.0.0.1:20172 "

export EDITOR=vim

source <(kubectl completion zsh)
alias k=kubectl
complete -F __start_kubectl k

alias z_save="_zlua"
alias z="z_save -I"
export _ZL_ECHO=1
export _ZL_HYPHEN=1
export _ZL_MATCH_MODE=1

export PATH="$HOME/.poetry/bin:$PATH"



eval "$(atuin init zsh)"


# 
# zle -N  atuin_fzf
# bindkey -r "^R" 
# bindkey "^R" atuin_fzf

alias emacs='emacs -nw'
