source ~/.zsh/antigen.zsh

antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle extract 
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle autojump
antigen bundle z
antigen bundle d
antigen bundle cargo
#antigen bundle kubectl
antigen bundle zsh-users/zsh-autosuggestions
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme
# https://github.com/zsh-users/antigen/issues/675#issuecomment-452764451
THEME=robbyrussell
antigen list | grep $THEME; if [ $? -ne 0 ]; then antigen theme $THEME; fi

# Tell Antigen that you're done.
antigen apply

export PATH=~/bin:$PATH
export PATH=/home/oaa/work/trantect/saas/tx-startup/tx/scripts:$PATH


export PATH=$PATH:/home/oaa/work/trantect/saas/tx-startup/dev-script
export PATH=$PATH:/usr/local/go/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/oaa/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/home/oaa/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/oaa/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/oaa/bin/google-cloud-sdk/completion.zsh.inc'; fi



export PATH=/home/oaa/.tiup/bin:$PATH


alias lock="gnome-screensaver-command -l"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='fd'
alias gpm="git pull origin master"


# nvm config
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# emacs-lab
export PATH=/home/oaa/lab/emacs-lab/redguardtoo:$PATH
export PATH=$PATH:/home/oaa/.local/bin

export GOPATH="$HOME/go"; 
export GOROOT="$HOME/.go"; 
export PATH="$GOPATH/bin:$PATH"; 
# g-install: do NOT edit, see https://github.com/stefanmaric/g
alias gvm="$GOPATH/bin/g"; 
# g-install: do NOT edit, see https://github.com/stefanmaric/g


# go config
go env -w GO111MODULE=on
go env -w  GOPROXY=https://goproxy.cn


source ~/.cargo/env 
